### ISSUE TITLE
(v1.3.5) Cannot read properties of undefined (reading 'color')

### ISSUE THREAD

**Issue by KovSer** [LJPc-solutions/freescout-calendar-module#7]
calendar-app.js:209 Uncaught TypeError: Cannot read properties of undefined (reading 'color')
    at beforeCreateSchedule (calendar-app.js:209:33)
    at r.invoke (tui-code-snippet.min.js:7:17459)
    at r.fire (tui-code-snippet.min.js:7:17262)
    at S._onBeforeCreate (tui-calendar.min.js:7:79670)
    at r.invoke (tui-code-snippet.min.js:7:17459)
    at r.fire (tui-code-snippet.min.js:7:17262)
    at D (tui-calendar.min.js:9:28858)
    at r.invoke (tui-code-snippet.min.js:7:17459)
    at r.fire (tui-code-snippet.min.js:7:17262)
    at f._onClickCreateSchedule (tui-calendar.min.js:7:61164)
![Screenshot_1](https://user-images.githubusercontent.com/85105862/172063298-bf45f3b1-f640-49f6-8364-041ac49fb02b.jpg)

**Comment by KovSer** [comment]
Sorry, need to created one calendar))
